------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- CARS MODEL --

INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD YUAN PLUS');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD TAN');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD YUAN PRO');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD SEAL');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD HAN');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD DOLPHIN PLUS');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD DOLPHIN');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD DOLPHIN MINI');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD SONG PRO DM-i');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('SONG PLUS PREMIUM DM-i');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD SONG PLUS DM-i');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD KING DM-i');
INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD SHARK');

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- CARS INFO --

INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN001', 'BYDAMEBR0015W', 1, 0); 
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN002', 'BYDAMEBR0021W', 1, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN003', 'BYDAMEBR0099W', 2, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN004', 'BYDAMEBR0077W', 4, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN005', 'BYDAMEBR0066W', 5, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN006', 'BYDAMEBR0055W', 6, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN007', 'BYDAMEBR0044W', 7, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN008', 'BYDAMEBR0033W', 8, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN009', 'BYDAMEBR0022W', 9, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN010', 'BYDAMEBR0011W', 10, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN011', 'BYDAMEBR0001W', 11, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN012', 'BYDAMEBR0020W', 12, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN013', 'BYDAMEBR0030W', 13, 0);
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN014', 'BYDAMEBR0015W', 1, 0); 
INSERT INTO CAR_INFO (VIN, DEALER_CODE, CAR_MODEL_ID, IS_SOLD) VALUES ('VIN015', 'BYDAMEBR0015W', 1, 0);
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 31, 31, 33, 33, 'Pintura exterior com pequeno arranhão no painel lateral traseiro, necessita de retoque', 1, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, 'Barulho anormal identificado na suspensão dianteira durante teste de rodagem', 1, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 20.0, 11.5, 1, 31, 31, 33, 33, '', 2, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 50.0, 11.5, 1, 32, 32, 33, 33, '', 3, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 20.5, 11.5, 1, 32, 32, 33, 33, '', 4, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 25.5, 11.5, 1, 32, 32, 33, 33, '', 5, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 7.5, 11.5, 1, 32, 32, 33, 33, '', 6, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 7.5, 11.5, 1, 32, 32, 33, 33, '', 7, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 7.5, 11.5, 1, 32, 32, 33, 33, '', 8, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 7.5, 11.5, 1, 32, 32, 33, 33, '', 9, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 1, NULL);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 10, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 11, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'),  0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 12, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 13, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 14, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS, CAR_ID, CREATED_DATE, LAST_MODIFIED_DATE, PENDING, RESOLVED_DATE)
VALUES(5, 5, 87.5, 11.5, 1, 32, 32, 33, 33, '', 15, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'), TO_TIMESTAMP('27/02/2025 17:30', 'DD/MM/YYYY HH24:MI'), 0, TO_TIMESTAMP('23/01/2025 14:30', 'DD/MM/YYYY HH24:MI'));




 
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('vin');
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('soc');
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('tire'); 
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('battery12V'); 
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('extraImages'); 