INSERT INTO CAR_MODEL (CAR_MODEL_NAME) VALUES ('BYD KING');

INSERT INTO CAR_INFO (CHASSI_NUMBER, DEALER_CODE, CAR_MODEL)
VALUES ('CHASSI001', 'BYDAMEBR0076W', 1);

INSERT INTO PDI_INFO (CREATE_BY_USER_ID, DEALER_CODE, LAST_MODIFIED_BY_USER_ID, SOC_PERCENTAGE, BATTERY12V_VOLTAGE, FIVE_MINUTES_HYBRID_CHECK, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE, TIRE_PRESSURE_TE, USER_COMMENTS)
VALUES(5, 'BYDAMEBR0076W', 1, 87.5, 11.5, 0, 50, 51, 52, 53, "Carro top");

INSERT INTO CAR_TO_PDI (CAR_ID, PDI_ID)
  VALUES(1, 1);


INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('CHASSI');
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('SOC');
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('PNEU');
INSERT INTO PDI_IMAGE_TYPE (PDI_IMAGE_TYPE_NAME) VALUES ('BATERIA12V_VOLTAGE');