INSERT INTO Cars (CHASSI_NUMBER, DEALER_CODE, MODEL, PDI_IDS)
VALUES ('CHASSI001', 'BYDAMEBR0076W', 'Modelo A', '{"pdi_ids": [1,2]}');

INSERT INTO Cars (CHASSI_NUMBER, DEALER_CODE, MODEL, PDI_IDS)
VALUES ('CHASSI002', 'BYDAMEBR0077W', 'Modelo B', '{"pdi_ids": [3,4,5]}');

INSERT INTO Cars (CHASSI_NUMBER, DEALER_CODE, MODEL, PDI_IDS)
VALUES ('CHASSI003', 'BYDAMEBR0078W', 'Modelo C', '{"pdi_ids": [6]}');

INSERT INTO Cars (CHASSI_NUMBER, DEALER_CODE, MODEL, PDI_IDS)
VALUES ('CHASSI004', 'BYDAMEBR0079W', 'Modelo D', '{"pdi_ids": [7,8]}');

INSERT INTO Cars (CHASSI_NUMBER, DEALER_CODE, MODEL, PDI_IDS)
VALUES ('CHASSI005', 'BYDAMEBR0080W', 'Modelo E', '{"pdi_ids": [9,10,11]}');



-- PDIs para o carro com CHASSI 'CHASSI001' (CAR_ID = 1)
INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    1, 101, 'BYDAMEBR0076W', TO_DATE('2025-01-15','YYYY-MM-DD'), 'CHASSI001',
    1, 0.85, 2, 12, 3,
    1, 32.5, 32.7, 33.0, 33.2, 4, 5, 6, 'Verificação ok'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    1, 102, 'BYDAMEBR0076W', TO_DATE('2025-02-10','YYYY-MM-DD'), 'CHASSI001',
    7, 0.90, 8, 13, 9,
    0, 31.8, 31.9, 32.0, 32.1, 10, 11, 12, 'PDI realizado sem problemas'
);

-- PDIs para o carro com CHASSI 'CHASSI002' (CAR_ID = 2)
INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    2, 201, 'BYDAMEBR0077W', TO_DATE('2025-01-20','YYYY-MM-DD'), 'CHASSI002',
    13, 0.75, 14, 11, 15,
    1, 30.5, 30.7, 30.8, 30.6, 16, 17, 18, 'Tudo certo'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    2, 202, 'BYDAMEBR0077W', TO_DATE('2025-02-01','YYYY-MM-DD'), 'CHASSI002',
    19, 0.80, 20, 12, 21,
    1, 31.0, 31.1, 31.2, 31.3, 22, 23, 24, 'Pequena falha detectada'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    2, 203, 'BYDAMEBR0077W', TO_DATE('2025-03-01','YYYY-MM-DD'), 'CHASSI002',
    25, 0.95, 26, 13, 27,
    0, 32.2, 32.3, 32.4, 32.5, 28, 29, 30, 'Revisão completa'
);

-- PDIs para o carro com CHASSI 'CHASSI003' (CAR_ID = 3)
INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    3, 301, 'BYDAMEBR0078W', TO_DATE('2025-01-05','YYYY-MM-DD'), 'CHASSI003',
    31, 0.65, 32, 10, 33,
    1, 29.5, 29.7, 29.8, 29.6, 34, 35, 36, 'Inspecionado com observações'
);

-- PDIs para o carro com CHASSI 'CHASSI004' (CAR_ID = 4)
INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    4, 401, 'BYDAMEBR0079W', TO_DATE('2025-02-15','YYYY-MM-DD'), 'CHASSI004',
    37, 0.88, 38, 14, 39,
    0, 33.5, 33.6, 33.7, 33.8, 40, 41, 42, 'Sem pendências'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    4, 402, 'BYDAMEBR0079W', TO_DATE('2025-03-10','YYYY-MM-DD'), 'CHASSI004',
    43, 0.92, 44, 15, 45,
    1, 34.0, 34.1, 34.2, 34.3, 46, 47, 48, 'Nova inspeção realizada'
);

-- PDIs para o carro com CHASSI 'CHASSI005' (CAR_ID = 5)
INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    5, 501, 'BYDAMEBR0080W', TO_DATE('2025-01-25','YYYY-MM-DD'), 'CHASSI005',
    49, 0.70, 50, 11, 51,
    1, 30.0, 30.1, 30.2, 30.3, 52, 53, 54, 'Revisão sem intercorrências'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    5, 502, 'BYDAMEBR0080W', TO_DATE('2025-02-20','YYYY-MM-DD'), 'CHASSI005',
    55, 0.78, 56, 12, 57,
    0, 30.5, 30.6, 30.7, 30.8, 58, 59, 60, 'Ajuste necessário'
);

INSERT INTO Pdi_history (
    CAR_ID, USER_ID, DEALER_CODE, CREATED_AT, CHASSI_NUMBER,
    CHASSI_IMAGE_ID, SOC_PERCENTAGE, SOC_IMAGE_ID, BATTERYV12, BATTERYV12_IMAGE_ID,
    FIVE_MINUTES_HYBRID, TIRE_PRESSURE_DD, TIRE_PRESSURE_TD, TIRE_PRESSURE_DE,
    TIRE_PRESSURE_TE, TIRE_PRESSURE_IMAGE_ID, EXTRA_IMAGE_ID, EXTRA2_IMAGE_ID, EXTRA_TEXT
)
VALUES (
    5, 503, 'BYDAMEBR0080W', TO_DATE('2025-03-15','YYYY-MM-DD'), 'CHASSI005',
    61, 0.85, 62, 13, 63,
    1, 31.0, 31.1, 31.2, 31.3, 64, 65, 66, 'Tudo OK'
);


UPDATE Cars 
SET MODEL = 'BYD YUAN PLUS'
WHERE CHASSI_NUMBER = 'CHASSI001';

UPDATE Cars 
SET MODEL = 'BYD TAN'
WHERE CHASSI_NUMBER = 'CHASSI002';

UPDATE Cars 
SET MODEL = 'BYD YUAN PRO'
WHERE CHASSI_NUMBER = 'CHASSI003';

UPDATE Cars 
SET MODEL = 'BYD SEAL'
WHERE CHASSI_NUMBER = 'CHASSI004';

UPDATE Cars 
SET MODEL = 'BYD HAN'
WHERE CHASSI_NUMBER = 'CHASSI005';
